# linear algebra


In [1]:
import numpy as np  

In [2]:
A = np.array([
    [2, -1],
    [0, 3]
])      

B = np.array([
    [1, 2],
    [3, -4]
])      

B = np.array([
    [4, 1],
    [-2, 1]
])    

In [4]:
print("A + B is ", A+B)

A + B is  [[ 6  0]
 [-2  4]]


In [5]:
print("A*B=", A@B)
print("A*B (using np.dot)=", np.dot(A, B))

A*B= [[10  1]
 [-6  3]]
A*B (using np.dot)= [[10  1]
 [-6  3]]


In [8]:
print("3A - 2B=", 3*A - 2*B)

3A - 2B= [[-2 -5]
 [ 4  7]]


In [10]:
print("determinant of A=", np.linalg.det(A))

determinant of A= 6.0


In [12]:
# print(A.shape)
rows, cols= A.shape
print(f"Matrix A has {rows} rows and {cols} columns.")
detA=np.linalg.det(A)

if rows != cols:
    print("Matrix A is not square, so it is not invertible.")

if detA != 0:
    print("Matrix A is invertible.")

Ainv= np.linalg.inv(A)   #matrix inverse=(1/detA) * adj(A)
print("Inverse of A is:\n", Ainv)

adjA= detA * Ainv
print("Adjoint of A is:\n", adjA)

Matrix A has 2 rows and 2 columns.
Matrix A is invertible.
Inverse of A is:
 [[0.5        0.16666667]
 [0.         0.33333333]]
Adjoint of A is:
 [[3. 1.]
 [0. 2.]]


In [13]:
eigenval, eigenveec= np.linalg.eig(A)
print("eigenvalues of A =", eigenval)
print(eigenval[0])
print(eigenval[1])
print("eigenvectors of A =\n", eigenveec)

eigenvalues of A = [2. 3.]
2.0
3.0
eigenvectors of A =
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


In [15]:
x=np.array([
    [1,4,1.5,100],
    [1,6,2.0,150]
]
)
y=np.array([
    [20],
    [30]
])
a=x.T@x
b=x.T@y
beta=np.linalg.pinv(a)@b
print("Coefficients (beta) are:\n", beta)
print(y)

Coefficients (beta) are:
 [[-0.00079866]
 [ 0.00798658]
 [ 0.00159732]
 [ 0.19966456]]
[[20]
 [30]]


In [16]:
car3 = np.array([[1, 8, 3.0, 200]])
price_car3 = car3 @ beta
print("Price for Car 3:", price_car3[0, 0])

Price for Car 3: 40.00079865825058
